<h2>Project 3: Na&iuml;ve Bayes and the Perceptron</h2>

<blockquote>
    <center>
    <img src="nb.png" width="200px" />
    </center>
      <p><cite><center>"All models are wrong, but some are useful."<br>
       -- George E.P. Box
      </center></cite></p>
</blockquote>

<h3>Introduction</h3>
<!--Aðalbrandr-->

<p>A&eth;albrandr is visiting America from Norway and has been having the hardest time distinguishing boys and girls because of the weird American names like Jack and Jane.  This has been causing lots of problems for A&eth;albrandr when he goes on dates. When he heard that Cornell has a Machine Learning class, he asked that we help him identify the gender of a person based on their name to the best of our ability.  In this project, you will implement Na&iuml;ve Bayes to predict if a name is male or female. </p>

<strong>How to submit:</strong> You can submit your code using the red <strong>Submit</strong> button above. This button will send any code below surrounded by <strong>#&lt;GRADED&gt;</strong><strong>#&lt;/GRADED&gt;</strong> tags below to the autograder, which will then run several tests over your code. By clicking on the <strong>Details</strong> dropdown next to the Submit button, you will be able to view your submission report once the autograder has completed running. This submission report contains a summary of the tests you have failed or passed, as well as a log of any errors generated by your code when we ran it.

Note that this may take a while depending on how long your code takes to run! Once your code is submitted you may navigate away from the page as you desire -- the most recent submission report will always be available from the Details menu.

<p><strong>Evaluation:</strong> Your code will be autograded for technical
correctness and--on some assignments--speed. Please <em>do not</em> change the names of any provided functions or classes within the code, or you will wreak havoc on the autograder. Furthermore, <em>any code not surrounded by <strong>#&lt;GRADED&gt;</strong><strong>#&lt;/GRADED&gt;</strong> tags will not be run by the autograder</em>. However, the correctness of your implementation -- not the autograder's output -- will be the final judge of your score.  If necessary, we will review and grade assignments individually to ensure that you receive due credit for your work.

<p><strong>Academic Integrity:</strong> We will be checking your code against other submissions in the class for logical redundancy. If you copy someone else's code and submit it with minor changes, we will know. These cheat detectors are quite hard to fool, so please don't try. We trust you all to submit your own work only; <em>please</em> don't let us down. If you do, we will pursue the strongest consequences available to us.

<p><strong>Getting Help:</strong> You are not alone!  If you find yourself stuck  on something, contact the course staff for help.  Office hours, section, and the <a href="https://piazza.com/class/iyag4nk2rsxsv">Piazza</a> are there for your support; please use them.  If you can't make our office hours, let us know and we will schedule more.  We want these projects to be rewarding and instructional, not frustrating and demoralizing.  But, we don't know when or how to help unless you ask.
  

<h3> Of boys and girls </h3>

<p> Take a look at the files <code>girls.train</code> and <code>boys.train</code>. For example with the unix command <pre>cat girls.train</pre> 
<pre>
...
Addisyn
Danika
Emilee
Aurora
Julianna
Sophia
Kaylyn
Litzy
Hadassah
</pre>
Believe it or not, these are all more or less common girl names. The problem with the current file is that the names are in plain text, which makes it hard for a machine learning algorithm to do anything useful with them. We therefore need to transform them into some vector format, where each name becomes a vector that represents a point in some high dimensional input space. </p>

<p>That is exactly what the following Python function <code>name2features</code> does: </p>

In [1]:
#<GRADED>
import numpy as np
#</GRADED>
import sys

# add p03 folder
sys.path.insert(0, './p03/')

%matplotlib inline

In [2]:
def hashfeatures(baby, B):
    v = np.zeros(B)
    for letter in baby:
        v[hash(letter) % B] = 1
    return v

In [3]:
def name2features(filename, B=128, LoadFile=True):
    """
    Output:
    X : n feature vectors of dimension B, (nxB)
    """
    # read in baby names
    if LoadFile:
        with open(filename, 'r') as f:
            babynames = [x.rstrip() for x in f.readlines() if len(x) > 0]
    else:
        babynames = filename.split('\n')
    n = len(babynames)
    X = np.zeros((n, B))
    for i in range(n):
        X[i,:] = hashfeatures(babynames[i], B)
    return X

It reads every name in the given file and converts it into a 128-dimensional feature vector. </p> 

<p>Can you figure out what the features are? (Understanding how these features are constructed will help you later on in the competition.)<br></p>

<p>We have provided you with a python function <code>genTrainFeatures</code>, which calls this script, transforms the names into features and loads them into memory. 

In [4]:
def genTrainFeatures(dimension=128):
    """
    function [x,y]=genTrainFeatures
    
    This function calls the python script "name2features.py" 
    to convert names into feature vectors and loads in the training data. 
    
    
    Output: 
    x: n feature vectors of dimensionality d [d,n]
    y: n labels (-1 = girl, +1 = boy)
    """
    
    # Load in the data
    Xgirls = name2features("girls.train", B=dimension)
    Xboys = name2features("boys.train", B=dimension)
    X = np.concatenate([Xgirls, Xboys])
    
    # Generate Labels
    Y = np.concatenate([-np.ones(len(Xgirls)), np.ones(len(Xboys))])
    
    # shuffle data into random order
    ii = np.random.permutation([i for i in range(len(Y))])
    
    return X[ii, :], Y[ii]

You can call the following command to load in the features and the labels of all boys and girls names. 

In [5]:
X,Y = genTrainFeatures(128)

<h3> The Na&iuml;ve Bayes Classifier </h3>

<p> The Na&iuml;ve Bayes classifier is a linear classifier based on Bayes Rule. The following questions will ask you to finish these functions in a pre-defined order. <br>
<strong>As a general rule, you should avoid tight loops at all cost.</strong></p>
<p>(a) Estimate the class probability P(Y) in 
<b><code>naivebayesPY</code></b>
. This should return the probability that a sample in the training set is positive or negative, independent of its features.
</p>



In [6]:
#<GRADED>
def naivebayesPY(x,y):
    """
    naivebayesPY(x,y) returns [pos,neg]

    Computation of P(Y)
    Input:
        x : n input vectors of d dimensions (nxd)
        y : n labels (-1 or +1) (nx1)

    Output:
    pos: probability p(y=1)
    neg: probability p(y=-1)
    """
    
    # add one positive and negative example to avoid division by zero ("plus-one smoothing")
    y = np.concatenate([y, [-1,1]])
    n = len(y)
    ## fill in code here    
    pos=np.sum([y==1])/len(y)
    neg=np.sum([y==-1])/len(y)
    #raise NotImplementedError('Your code goes here!')
    return pos,neg

#</GRADED>

pos,neg = naivebayesPY(X,Y)

<p>(b) Estimate the conditional probabilities P(X|Y) in 
<b><code>naivebayesPXY</code></b>
.  Use a <b>multinomial</b> distribution as model. This will return the probability vectors  for all features given a class label.
</p> 

In [28]:
#<GRADED>
def naivebayesPXY(x,y):
    """
    naivebayesPXY(x,y) returns [posprob,negprob]
    
    Computation of P(X|Y)
    Input:
        x : n input vectors of d dimensions (nxd)
        y : n labels (-1 or +1) (nx1)
    
    Output:
    posprob: probability vector of p(x|y=1) (1xd)
    negprob: probability vector of p(x|y=-1) (1xd)
    """
    
    # add one positive and negative example to avoid division by zero ("plus-one smoothing")
    n, d = x.shape
    x = np.concatenate([x, np.ones((2,d))])
    y = np.concatenate([y, [-1,1]])
    n, d = x.shape
    
    plus=np.argwhere(y==1)
    minus=np.argwhere(y==-1)
    posprob=np.sum(x[plus],axis=0)/plus.shape[0]
    negprob=np.sum(x[minus],axis=0)/minus.shape[0]
    print(posprob.shape)
    return posprob,negprob
    ## fill in code here
    #raise NotImplementedError('Your code goes here!')
    
#</GRADED>

posprob,negprob = naivebayesPXY(X,Y)

(1, 128)


<p>(c) Solve for the log ratio, $\log\left(\frac{P(Y=1 | X = xtest)}{P(Y=-1|X= xtest)}\right)$, using Bayes Rule.
 Implement this in 
<b><code>naivebayes</code></b>.
</p>



In [53]:
#<GRADED>
def naivebayes(x,y,xtest):
    """
    naivebayes(x,y) returns logratio 
    
    Computation of log P(Y|X=x1) using Bayes Rule
    Input:
    x : n input vectors of d dimensions (nxd)
    y : n labels (-1 or +1)
    xtest: input vector of d dimensions (1xd)
    
    Output:
    logratio: log (P(Y = 1|X=xtest)/P(Y=-1|X=xtest))
    """
    
    ## fill in code here
   # raise NotImplementedError('Your code goes here!')
    posprob,negprob = naivebayesPXY(x,y)
    logpos=np.log(np.inner(posprob.flatten(),xtest))
    logneg=np.log(np.inner(negprob.flatten(),xtest))
    #(0.1,0.2,0,3)
    return logpos-logneg
#</GRADED>

p = naivebayes(X,Y,X[0,:])

In [49]:
pos=np.array([[0.4],[0.5],[0.5],[.9],[0.87]])
x=np.array([0,0,1,0,1])
np.inner(pos,pos)

ValueError: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

In [33]:
print(x)
print(pos)

[[1 0 1 1 1]
 [1 1 0 1 1]
 [0 0 1 0 1]]
[[0.4 ]
 [0.5 ]
 [0.5 ]
 [0.9 ]
 [0.87]]


<p>(d) Naïve Bayes can also be written as a linear classifier. Implement this in 
<b><code>naivebayesCL</code></b>.

In [99]:
#<GRADED>
def naivebayesCL(x,y):
    """
    naivebayesCL(x,y) returns [w,b]
    Implementation of a Naive Bayes classifier
    Input:
    x : n input vectors of d dimensions (nxd)
    y : n labels (-1 or +1)

    Output:
    w : weight vector of d dimensions
    b : bias (scalar)
    """
    
    n, d = x.shape
    ## fill in code here
    posprob,negprob = naivebayesPXY(x,y)
    w=(np.log(posprob)-np.log(negprob)).flatten()
    #print(w.shape)
    pos,neg=naivebayesPY(x,y)
    b=np.log(pos)-np.log(neg)
    #raise NotImplementedError('Your code goes here!')
    return w,b 
#</GRADED>

w,b = naivebayesCL(X,Y)

<p>(e) Implement 
<b><code>classifyLinear</code></b>
 that applies a linear weight vector and bias to a set of input vectors and outputs their predictions.  (You can use your answer from the previous project.)
 
 

In [100]:
X.shape

(1200, 128)

In [101]:
#<GRADED>
def classifyLinear(x,w,b=0):
    """
    classifyLinear(x,w,b) returns preds
    
    Make predictions with a linear classifier
    Input:
    x : n input vectors of d dimensions (nxd)
    w : weight vector of d dimensions
    b : bias (optional)
    
    
    Output:
    preds: predictions
    """
    w=np.expand_dims(w,axis=0)
    a=w.dot(x.T)+b
    a=a.flatten()
    print(a)
    a[a>0]=1
    a[a<0]=-1
    print(a)
    ## fill in code here
    #raise NotImplementedError('Your code goes here!')
    return a
#</GRADED>

print('Training error: %.2f%%' % (100 *(classifyLinear(X, w, b) != Y).mean()))

[-0.9260421  -0.5110544   1.94876299 ...  0.97735422  0.96543346
 -0.24720066]
[-1. -1.  1. ...  1.  1. -1.]
Training error: 29.92%


You can now test your code with the following interactive name classification script:

In [102]:
a=np.array([1,-1,1,3])

In [103]:
a[a>0]=1

In [ ]:
DIMS = 128
print('Loading data ...')
X,Y = genTrainFeatures(DIMS)
print('Training classifier ...')
w,b=naivebayesCL(X,Y)
error = np.mean(classifyLinear(X,w,b) != Y)
print('Training error: %.2f%%' % (100 * error))

while True:
    print('Please enter your name>')
    yourname = input()
    if len(yourname) < 1:
        break
    xtest = name2features(yourname,B=DIMS,LoadFile=False)
    pred = classifyLinear(xtest,w,b)[0]
    if pred > 0:
        print("%s, I am sure you are a nice boy.\n" % yourname)
    else:
        print("%s, I am sure you are a nice girl.\n" % yourname)

Loading data ...
Training classifier ...
[-1.424436    1.9462046   1.2979562  ...  0.67474079 -0.71878435
 -0.23751055]
[-1.  1.  1. ...  1. -1. -1.]
Training error: 29.92%
Please enter your name>
Evan
[0.45281457]
[1.]
Evan, I am sure you are a nice boy.

Please enter your name>
David
[0.81862736]
[1.]
David, I am sure you are a nice boy.

Please enter your name>
Lucy
[-0.20462293]
[-1.]
Lucy, I am sure you are a nice girl.

Please enter your name>


<h3> Feature Extraction (Competition)</h3>

<p>(e) (<b>optional</b>) As always, this programming project also includes a competition.  We will rank all submissions by how well your Na&iuml;ve Bayes classifier performs on a secret test set. If you want to improve your classifier modify <code>name2features2</code> below.   The automatic reader will use your Python script to extract features and train your classifier on the same names training set by calling the function with only one argument--the name of a file containing a list of names.  The given implementation is the same as the given <code>name2features</code> above.
</p>
  

In [ ]:
#<GRADED>
def hashfeatures(baby, B):
    v = np.zeros(B)
    for letter in baby:
        v[hash(letter) % B] = 1
    return v

def name2features2(filename, B=128, LoadFile=True):
    """
    Output:
    X : n feature vectors of dimension B, (nxB)
    """
    # read in baby names
    if LoadFile:
        with open(filename, 'r') as f:
            babynames = [x.rstrip() for x in f.readlines() if len(x) > 0]
    else:
        babynames = filename.split('\n')
    n = len(babynames)
    X = np.zeros((n, B))
    for i in range(n):
        X[i,:] = hashfeatures(babynames[i], B)
    return X

#</GRADED>

<h4>Credits</h4>
  Parts of this webpage were copied from or heavily inspired by John DeNero's and Dan Klein's (awesome) <a href="http://ai.berkeley.edu/project_overview.html">Pacman class</a>. The name classification idea originates from <a href="http://nickm.com">Nick Montfort</a>.